### ISSUE TITLE
Поля ввода Фамилии, Имени и Должности: возможность ввода цифр и специальных символов

### ISSUE THREAD

**Issue by MangolSergey** [vliplianina/practice-task1#17]
Окружение:
Модель устройства: Redmi 3S
Версия ОС: Android 6.0.1 MMB29M

Шаги воспроизведения:
1) Переходим в список сотрудников
2) Нажимаем "Добавить"
3) В поля Фамилия и(или) Имя и(или) Должность вводим например: 
- Фамилия: Манголь%%%;
- Имя: Сергей55;
- Должность: Manager5%
4) Нажимаем Сохранить.

Ожидаемый результат:
- Появление ошибки "Некорректные данные"
 
Фактический результат:
- Сохранение нового сотрудника и добавление его в Список сотрудников

**Comment by henry-monstein** [comment]
Баг воспроизведен

- OS: Android 9 Pie
- Xiaomi Mi A2

**Comment by Janekushar** [comment]
Баг воспроизведен

- OS: Android 8,1 Oreo
- Meizu 16th

**Comment by kozant** [comment]
Баг воспроизведён

Модель устройства: Xiaomi Redmi 6
Версия ОС: Android 8.1.0 O11019

**Comment by vliplianina** [comment]
Не баг. В требованиях не сказано, что нельзя вводить спец.символы или цифры. 
Можно завести как запрос на улучшение, но обосновать, почему предлагается ввести данное ограничение.
Примечание: в данной ситуации ограничение было бы избыточным.
